// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBEbIhBhnavQ96k9vMP6randuXnQWgznI',
    appId: '1:1019199433165:web:cf8c3180c8b7dd111f7c84',
    messagingSenderId: '1019199433165',
    projectId: 'storepass-e4a43',
    authDomain: 'storepass-e4a43.firebaseapp.com',
    storageBucket: 'storepass-e4a43.firebasestorage.app',
    measurementId: 'G-BSNXLPRDHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt1mA1PdVpg1jR4gXku0u8gCrA9q4dIcg',
    appId: '1:1019199433165:android:cf4b4da5c89fc3d31f7c84',
    messagingSenderId: '1019199433165',
    projectId: 'storepass-e4a43',
    storageBucket: 'storepass-e4a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaV7IigLGeMeL0niAwj65Yz5isMZqe1T0',
    appId: '1:1019199433165:ios:8a165bf4f2d18c801f7c84',
    messagingSenderId: '1019199433165',
    projectId: 'storepass-e4a43',
    storageBucket: 'storepass-e4a43.firebasestorage.app',
    iosClientId: '1019199433165-c219j40jok9vfd4rjoidqdihg25qcfem.apps.googleusercontent.com',
    iosBundleId: 'uz.angrykitten.storepass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaV7IigLGeMeL0niAwj65Yz5isMZqe1T0',
    appId: '1:1019199433165:ios:8a165bf4f2d18c801f7c84',
    messagingSenderId: '1019199433165',
    projectId: 'storepass-e4a43',
    storageBucket: 'storepass-e4a43.firebasestorage.app',
    iosClientId: '1019199433165-c219j40jok9vfd4rjoidqdihg25qcfem.apps.googleusercontent.com',
    iosBundleId: 'uz.angrykitten.storepass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBEbIhBhnavQ96k9vMP6randuXnQWgznI',
    appId: '1:1019199433165:web:e8ce94457ce0c8bd1f7c84',
    messagingSenderId: '1019199433165',
    projectId: 'storepass-e4a43',
    authDomain: 'storepass-e4a43.firebaseapp.com',
    storageBucket: 'storepass-e4a43.firebasestorage.app',
    measurementId: 'G-8HDFG39297',
  );
}
